### ISSUE TITLE
Glitching example

### ISSUE THREAD

**Issue by dhoizner** [SpaceTypeContinuum/generative-typography#1]
Hiya @kyeah! 

I didn't see this in time to try and join the class, but have been working through some of the sketches here- i hope that's okay!

I think the x-nudge on [4L - Image copying (by row; x-nudging)
](https://editor.p5js.org/kyeah/sketches/y137XUugc) might be too drastic? when i run the sketch as is, there is zero output, but if i lower the nudge to something like `random(10)-5` then i start getting output.

if i'm out of my lane and you'd prefer me to not raise issues here, just let me know :)

**Comment by kyeah** [comment]
Hi @dhoizner, sorry for the delayed response! Totally fine to follow along, and thanks for raising an issue ( : 

It seems to be working for me with the larger nudge, but it works with a smaller nudge as well so I've made that change in case others run into the same issue. Thanks 🙏 

Hope you're enjoying the materials so far!
